### ISSUE TITLE
Update a fileAccessObject to keep track of all users

### ISSUE THREAD

**Issue by azyx0083** [azyx0083/CSC207-WhatEver-46#3]
**Content of the feature**
Currently, there is no implementation regarding users. In our next step, we plan to add a login/signup feature, which requires a corresponding dataAccessObject to track current users.

**Importance of this new feature**
Support use cases regarding users

**To-do list**
- [ ] Create and implement the fileAccessObject class and interfaces
- [ ] Update other use cases to support user feature
- [ ] Prepare tests and possibly an in-memory version
